"""Typed read, proposal, approval and execution boundaries for support tools."""

from knora.tools.capabilities import (
    CapabilityDescriptor,
    CapabilityRegistry,
    ExternalScopeBinding,
    WorkspaceResourceAuthorizer,
)
from knora.tools.dispatch_envelope import DispatchEnvelope, HmacDispatchEnvelopeSigner
from knora.tools.execution import ExecutionResourceAuthorizer
from knora.tools.execution_types import (
    AcquireApplied,
    AcquireDenied,
    AcquireInProgress,
    AdmissionApplied,
    AdmissionDenied,
    DispatchAdmissionWitness,
    ExecutionFailed,
    ExecutionFenced,
    ExecutionIndeterminate,
    ExecutionInProgress,
    ExecutionRecoverySeed,
    ExecutionSucceeded,
    ProposalNotExecutable,
    ProviderTerminalFailureCode,
)
from knora.tools.gateway import (
    FakeSupportToolGateway,
    LookupTicketRequest,
    ProviderContractInvalid,
    ProviderIdempotencyConflict,
    ProviderObservationUnavailable,
    ProviderOutcomeFound,
    ProviderOutcomeNotFound,
    ProviderResourceNotFound,
    ProviderScopeDenied,
    ProviderUnavailable,
    ProviderWriteFailed,
    ProviderWriteIndeterminate,
    ProviderWriteSucceeded,
    SQLiteSupportToolGateway,
    SupportToolGateway,
    TicketLookupResult,
)
from knora.tools.in_memory_tool_action_store import InMemoryToolActionStore
from knora.tools.proposal_compatibility import CompatibilityCheckerV1
from knora.tools.proposal_integration import (
    ReferenceExecutionResourceAuthorizer,
    ReferenceProposalTargetVerifier,
    RegistryCapabilityResolver,
)
from knora.tools.proposal_store import ToolActionStore
from knora.tools.proposal_types import (
    ActorContext,
    AlreadyDecided,
    ApproveProposal,
    AuthorityProvenance,
    CapabilityResolver,
    ExecuteApprovedProposal,
    PolicyProvenance,
    ProposalApproved,
    ProposalCreated,
    ProposalDecision,
    ProposalProjection,
    ProposalRejected,
    ProposalTargetVerifier,
    ProposeWriteAction,
    ReconcileExecution,
    RejectProposal,
    ResolvedCapabilityContext,
    StaticCapabilityResolver,
    ToolProposalProjection,
    VerifiedProposalTarget,
)
from knora.tools.proposals import (
    ExecutionAuthorizer,
    HumanApprovalAuthorizer,
    WriteProposalWorkflow,
)
from knora.tools.read import ReadTool, ReadToolCommand
from knora.tools.references import (
    AuthorizedExternalResource,
    AuthorizedReferenceMintingResource,
    ExternalResourceReference,
    ExternalResourceReferenceMinter,
    InMemoryReferenceStore,
    ReferenceKey,
    ReferenceKeyRing,
    ReferenceRecord,
    ReferenceVerifier,
)
from knora.tools.sqlite_provider import SQLiteReferenceProvider

__all__ = [
    "AcquireApplied",
    "AcquireDenied",
    "AcquireInProgress",
    "ActorContext",
    "AdmissionApplied",
    "AdmissionDenied",
    "AlreadyDecided",
    "ApproveProposal",
    "AuthorityProvenance",
    "AuthorizedExternalResource",
    "AuthorizedReferenceMintingResource",
    "CapabilityDescriptor",
    "CapabilityRegistry",
    "CapabilityResolver",
    "CompatibilityCheckerV1",
    "DispatchAdmissionWitness",
    "DispatchEnvelope",
    "ExecuteApprovedProposal",
    "ExecutionAuthorizer",
    "ExecutionFailed",
    "ExecutionFenced",
    "ExecutionIndeterminate",
    "ExecutionInProgress",
    "ExecutionRecoverySeed",
    "ExecutionResourceAuthorizer",
    "ExecutionSucceeded",
    "ExternalResourceReference",
    "ExternalResourceReferenceMinter",
    "ExternalScopeBinding",
    "FakeSupportToolGateway",
    "HmacDispatchEnvelopeSigner",
    "HumanApprovalAuthorizer",
    "InMemoryReferenceStore",
    "InMemoryToolActionStore",
    "LookupTicketRequest",
    "PolicyProvenance",
    "ProposalApproved",
    "ProposalCreated",
    "ProposalDecision",
    "ProposalNotExecutable",
    "ProposalProjection",
    "ProposalRejected",
    "ProposalTargetVerifier",
    "ProposeWriteAction",
    "ProviderContractInvalid",
    "ProviderIdempotencyConflict",
    "ProviderObservationUnavailable",
    "ProviderOutcomeFound",
    "ProviderOutcomeNotFound",
    "ProviderResourceNotFound",
    "ProviderScopeDenied",
    "ProviderTerminalFailureCode",
    "ProviderUnavailable",
    "ProviderWriteFailed",
    "ProviderWriteIndeterminate",
    "ProviderWriteSucceeded",
    "ReadTool",
    "ReadToolCommand",
    "ReconcileExecution",
    "ReferenceKey",
    "ReferenceKeyRing",
    "ReferenceExecutionResourceAuthorizer",
    "ReferenceProposalTargetVerifier",
    "ReferenceRecord",
    "ReferenceVerifier",
    "RegistryCapabilityResolver",
    "RejectProposal",
    "ResolvedCapabilityContext",
    "SQLiteReferenceProvider",
    "SQLiteSupportToolGateway",
    "StaticCapabilityResolver",
    "SupportToolGateway",
    "TicketLookupResult",
    "ToolActionStore",
    "ToolProposalProjection",
    "VerifiedProposalTarget",
    "WorkspaceResourceAuthorizer",
    "WriteProposalWorkflow",
]
