"""Export and verify Knora's checked-in FastAPI OpenAPI contract."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "backend" / "src"
CONTRACT_PATH = ROOT / "docs" / "openapi.json"
MANIFEST_PATH = ROOT / "docs" / "openapi-manifest.json"
CLIENT_PATH = ROOT / "frontend" / "generated" / "knora-openapi.ts"
GENERATOR_ID = "knora-openapi-local"
GENERATOR_VERSION = "1.0.0"


def _canonical_json(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode(
        "utf-8"
    )


def _render_client(contract: dict[str, object]) -> bytes:
    def ts_type(schema: dict[str, object]) -> str:
        if "$ref" in schema:
            return str(schema["$ref"]).rsplit("/", 1)[-1]
        if "enum" in schema:
            return " | ".join(json.dumps(item) for item in schema["enum"])
        if "anyOf" in schema:
            return " | ".join(ts_type(item) for item in schema["anyOf"])
        schema_type = schema.get("type")
        if schema_type == "array":
            return f"Array<{ts_type(schema.get('items', {}))}>"
        if schema_type == "object":
            properties = schema.get("properties", {})
            if not properties:
                return "Record<string, unknown>"
            required = set(schema.get("required", []))
            fields = []
            for field in sorted(properties):
                optional = "" if field in required else "?"
                fields.append(f"  {field}{optional}: {ts_type(properties[field])};")
            return "{\n" + "\n".join(fields) + "\n}"
        return {
            "string": "string",
            "integer": "number",
            "number": "number",
            "boolean": "boolean",
            "null": "null",
        }.get(schema_type, "unknown")

    paths = sorted(contract.get("paths", {}))
    path_lines = "\n".join(f'  | "{path}"' for path in paths)
    schemas = contract.get("components", {}).get("schemas", {})
    schema_lines: list[str] = []
    for name in sorted(schemas):
        schema_lines.append(f"export type {name} = {ts_type(schemas[name])};")
    schema_text = "\n".join(schema_lines)
    response_by_path: list[str] = []
    for path in paths:
        operations = contract["paths"][path]
        response_type = "KnoraApiResponse"
        if isinstance(operations, dict):
            for operation in operations.values():
                if not isinstance(operation, dict):
                    continue
                response = operation.get("responses", {}).get("200") or operation.get(
                    "responses", {}
                ).get("202")
                content = response.get("content", {}) if isinstance(response, dict) else {}
                schema = content.get("application/json", {}).get("schema", {})
                if isinstance(schema, dict) and "$ref" in schema:
                    response_type = ts_type(schema)
                    break
        response_by_path.append(f'  "{path}": {response_type};')
    response_map = "\n".join(response_by_path)
    return (
        "// Generated by scripts/export_openapi.py; do not edit manually.\n"
        f"// Generator: {GENERATOR_ID}@{GENERATOR_VERSION}\n"
        "export const KNORA_OPENAPI_VERSION = "
        f'{json.dumps(contract["openapi"])} as const;\n'
        "export type KnoraApiPath =\n"
        f"{path_lines};\n\n"
        f"{schema_text}\n\n"
        "export type KnoraApiResponse =\n"
        "  | Record<string, unknown>\n"
        "  | unknown[]\n"
        "  | string\n"
        "  | number\n"
        "  | boolean\n"
        "  | null;\n\n"
        "export interface KnoraApiResponseByPath {\n"
        f"{response_map}\n"
        "}\n\n"
        "export type KnoraApiResponseFor<P extends KnoraApiPath> = "
        "KnoraApiResponseByPath[P];\n\n"
        "export interface KnoraClient {\n"
        "  request<P extends KnoraApiPath>(\n"
        "    path: P,\n"
        "    init?: RequestInit,\n"
        "  ): Promise<KnoraApiResponseFor<P>>;\n"
        "}\n"
    ).encode()


def _render_artifacts() -> tuple[bytes, bytes, bytes]:
    sys.path.insert(0, str(SOURCE_ROOT))
    from knora.main import app

    contract_data = app.openapi()
    contract = _canonical_json(contract_data)
    client = _render_client(contract_data)
    manifest = _canonical_json(
        {
            "contract": "docs/openapi.json",
            "openapi": json.loads(contract)["openapi"],
            "schema_version": 1,
            "sha256": hashlib.sha256(contract).hexdigest(),
            "source": "knora.main:app",
            "typescript_client": "frontend/generated/knora-openapi.ts",
            "typescript_client_generator": f"{GENERATOR_ID}@{GENERATOR_VERSION}",
            "typescript_client_sha256": hashlib.sha256(client).hexdigest(),
        }
    )
    return contract, manifest, client


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when checked-in artifacts differ from the current application schema",
    )
    args = parser.parse_args()
    contract, manifest, client = _render_artifacts()

    if args.check:
        current_contract = CONTRACT_PATH.read_bytes() if CONTRACT_PATH.exists() else None
        current_manifest = MANIFEST_PATH.read_bytes() if MANIFEST_PATH.exists() else None
        current_client = CLIENT_PATH.read_bytes() if CLIENT_PATH.exists() else None
        if current_contract != contract or current_manifest != manifest or current_client != client:
            print("OpenAPI artifacts are stale; run scripts/export_openapi.py", file=sys.stderr)
            return 1
        print("OpenAPI artifacts are current")
        return 0

    CONTRACT_PATH.write_bytes(contract)
    MANIFEST_PATH.write_bytes(manifest)
    CLIENT_PATH.parent.mkdir(parents=True, exist_ok=True)
    CLIENT_PATH.write_bytes(client)
    print(f"Wrote {CONTRACT_PATH}")
    print(f"Wrote {MANIFEST_PATH}")
    print(f"Wrote {CLIENT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
