"""Export and verify Knora's checked-in FastAPI OpenAPI contract."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "backend" / "src"
CONTRACT_PATH = ROOT / "docs" / "openapi.json"
MANIFEST_PATH = ROOT / "docs" / "openapi-manifest.json"
CLIENT_PATH = ROOT / "frontend" / "generated" / "knora-openapi.ts"


def _canonical_json(value: object) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode(
        "utf-8"
    )


def _render_client(contract: dict[str, object]) -> bytes:
    paths = sorted(contract.get("paths", {}))
    path_lines = "\n".join(f'  "{path}";' for path in paths)
    return (
        "// Generated by scripts/export_openapi.py; do not edit manually.\n"
        "export const KNORA_OPENAPI_VERSION = "
        f'{json.dumps(contract["openapi"])} as const;\n'
        "export type KnoraApiPath =\n"
        f"{path_lines}\n"
        "\n"
        "export interface KnoraClient {\n"
        "  request<T>(path: KnoraApiPath, init?: RequestInit): Promise<T>;\n"
        "}\n"
    ).encode()


def _render_artifacts() -> tuple[bytes, bytes, bytes]:
    sys.path.insert(0, str(SOURCE_ROOT))
    from knora.main import app

    contract_data = app.openapi()
    contract = _canonical_json(contract_data)
    client = _render_client(contract_data)
    manifest = _canonical_json(
        {
            "contract": "docs/openapi.json",
            "openapi": json.loads(contract)["openapi"],
            "schema_version": 1,
            "sha256": hashlib.sha256(contract).hexdigest(),
            "source": "knora.main:app",
            "typescript_client": "frontend/generated/knora-openapi.ts",
            "typescript_client_sha256": hashlib.sha256(client).hexdigest(),
        }
    )
    return contract, manifest, client


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when checked-in artifacts differ from the current application schema",
    )
    args = parser.parse_args()
    contract, manifest, client = _render_artifacts()

    if args.check:
        current_contract = CONTRACT_PATH.read_bytes() if CONTRACT_PATH.exists() else None
        current_manifest = MANIFEST_PATH.read_bytes() if MANIFEST_PATH.exists() else None
        current_client = CLIENT_PATH.read_bytes() if CLIENT_PATH.exists() else None
        if current_contract != contract or current_manifest != manifest or current_client != client:
            print("OpenAPI artifacts are stale; run scripts/export_openapi.py", file=sys.stderr)
            return 1
        print("OpenAPI artifacts are current")
        return 0

    CONTRACT_PATH.write_bytes(contract)
    MANIFEST_PATH.write_bytes(manifest)
    CLIENT_PATH.parent.mkdir(parents=True, exist_ok=True)
    CLIENT_PATH.write_bytes(client)
    print(f"Wrote {CONTRACT_PATH}")
    print(f"Wrote {MANIFEST_PATH}")
    print(f"Wrote {CLIENT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
